### ISSUE TITLE
[RateNewApp] Detect duplicate iOS and Android URL's

### ISSUE THREAD

**Issue by ecamach13** [BIDMCDigitalPsychiatry/AppMapDB#100]
is there a way to check for duplicates? 

maybe when someone tries adding a new app and they enter the same link it can have an error / popup that says "app link used for another app, check app library to ensure this is not a duplicate"

**Comment by cvanem** [comment]
Yes this is possible

**TODO**
- [x] Add duplication check.  When the user enters a link, and hits the next step, validate that the link does not already exist.
