### ISSUE TITLE
Quiz/Custom Search Filters

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/AppMapDB#107]
Another addition to the website, more pressing than the pop-up instructions, is the development of a quiz-like survey at the top of the website. 

This would be a banner on top of the 'search' bar but under the row of tabs (framework, community, etc). Essentially, this quiz would allow people to answer questions similar to those in the filter column and upon completion it would bring them to the list of apps that fit their criteria. If they choose a quiz question saying that they would like an app that is totally free, the system could check the 'totally free' box for them in the background.

Platform: What type of smartphone do you own?
Android 
Apple
Functionality: Do you have access to reliable internet through Wi-Fi or data plans? 
Yes
No [if no, then the website can check 'offline']
Cost: Are you looking for an app that is 
totally free 
free to download 
Privacy: Are you looking for an app that has a Privacy Policy detailing data use and purpose?
Yes [if yes, then the website would check 'has privacy policy' and 'declares data use and purpose']
No 
Clinical Foundation: Would you like an app that has conducted research studies that support the app's claims?
Yes [if yes, check supporting studies]
No
Supported Condition: Which of the following conditions are you looking for support for?
list all supported conditions (can choose one)

**Comment by cvanem** [comment]
@ecamach13 I have incorporated some of the old code and questions that this application used when we first started.  Please take a look at the new functionality by clicking the search wizard tab show in the picture.  I have published the changes, but you will need to log in as admin in order to see the new tab.

![image](https://user-images.githubusercontent.com/24579103/152729125-7efda834-bd8d-47df-a845-bdc445de54bd.png)

Please review and let me know what/if anything needs to be changed.

**Comment by ecamach13** [comment]
I don't see it yet for some reason. I have tried on both safari and chrome. 
![Uploading Screen Shot 2022-02-08 at 2.33.43 PM.png…]()

**Comment by ecamach13** [comment]
I don't see it yet for some reason. I have tried on both safari and chrome.
<img width="1309" alt="Screen Shot 2022-02-08 at 2 33 43 PM" src="https://user-images.githubusercontent.com/70787908/153062145-ffd39ea6-03e3-44a7-bf13-48b4a528de85.png">

**Comment by cvanem** [comment]
@ecamach13 Did you check on the home page?  The screenshot you posted is on the application library page.

I put it there for now as it makes the most sense as far as screen space usage, but we can definitely move it or change the implementation.  I just wanted you to look at it first before I spent too much time on anything further.

**Comment by ecamach13** [comment]
Oh I see it now! Got it, will take a look later.

**Comment by ecamach13** [comment]
Images attached her
![dont-know](https://user-images.githubusercontent.com/70787908/163575469-179c5d6b-a24c-48e9-b019-82776af53e8f.png)
![market-research](https://user-images.githubusercontent.com/70787908/163575477-4ee96b93-86ae-4169-baf4-50a344c5d69d.png)
![wifi](https://user-images.githubusercontent.com/70787908/163575497-56b54bc6-266e-4bff-970c-15a7f5a855a0.png)
![no-wifi](https://user-images.githubusercontent.com/70787908/163575512-c576c024-daaa-44f9-a2be-21db8576bee9.png)

e

**Comment by ecamach13** [comment]
![eng](https://user-images.githubusercontent.com/70787908/163575699-440ce6db-195a-469f-9c4d-76d40a9ab93c.png)
![translation](https://user-images.githubusercontent.com/70787908/163575720-245be040-f7c0-4404-8f93-a34e8029444a.png)
![touchless](https://user-images.githubuser
![export](https://user-images.githubusercontent.com/70787908/163575742-16f6f60c-9c3f-4bfb-a926-589bca709c53.png)
content.com/70787908/163575734-7e1980a6-59fe-4aa6-ba75-95253e895251.png)

![padlock](https://user-images.githubusercontent.com/70787908/163575781-b6048f62-22c5-45e0-8603-9bda81457b80.png)
![unlocked](https://u
![android](https://user-images.githubusercontent.com/70787908/163576007-074b589f-6a9c-4a61-947c-dec7ddfec0e1.png)
ser-
![apple](https://user-images.githubusercontent.com/70787908/163575997-416048b7-37a6-4f9f-ad28-6a3d8f2d7799.png)

![free](https://user-im
![world-wide-web](https://user-images.githubusercontent.com/70787908/163575990-9825d222-0e28-47f1-8d72-c4a0b2e74099.png)
ages.githubusercontent.com/70787908/163575970-abe30719-268e-4c6d-9783-9922b6b6e548.png)

![diary](https://user-images.githubusercontent.com/70787908/163575935-a253c1e6-6813-4873-a64b-175fe20230f0.png)
im
![dollar](https://user-images.githubusercontent.com/70787908/163575962-c23f6944-fcfd-4a29-be6a-aa2c1af3cb57.png)

![dial](https://user-images.githubusercontent.com/70787908/163575948-3892ebf6-c089-46c9-8e6e-aa53f4a5f73d.png)

![support](https://user-images.gith
![lotus](https://user-images.githubusercontent.com/70787908/163575889-8a572335-9dc8-416d-b4e5-c0e26c52f3d6.png)
ubusercontent.com/70787908/163575873-148518eb-cf35-4aac-a23a-af2e8234e8e0.png)

![sleeping](https://user-imag
![learning](https://user-images.githubusercontent.com/70787908/163575860-1d9c9a1e-fa38-4633-b100-fb02cab84d5b.png)
es.githubusercontent.com/70787908/163575837-5865a303-cc26-4ac6-bf63-43c1304a4362.png)
ag
![head](https://user-images.githubusercontent.com/70787908/163575812-df40c880-b49f-47bc-b60f-0c42b4eeb304.png)
es.githubusercontent.com/70787908/163575788-e0115018-4f0d-45d2-aa8a-b650f7be8251.png)
![capsules](https://user-images.githubusercontent.com/70787908/163575803-58b78987-7c29-4caa-ab36-a2027cb1c9c9.png)

**Comment by ecamach13** [comment]
![touchless](https://user-images.githubusercontent.com/70787908/163576156-12df2f54-0c28-4fe9-90d7-6a4701c65790.png)
![unlocked](https://user-images.githubusercontent.com/70787908/163576201-cd323b0b-4a1c-4534-bd04-f1ab3fdc7bd2.png)
![sleeping](https://user-images.githubusercontent.com/70787908/163576235-10c15208-a08f-4c01-8069-78ce60b97e73.png)
![support](https://user-images.githubusercontent.com/70787908/163576266-975e2271-f0f4-4a08-b21c-932f9d110a73.png)
![free](https://user-images.githubusercontent.com/70787908/163576304-35702c85-a918-4b25-bb3b-67bf59bc8608.png)
