### ISSUE TITLE
Error saving app rating 

### ISSUE THREAD

**Issue by ecamach13** [BIDMCDigitalPsychiatry/AppMapDB#108]
Someone rating an app sent me this issue they are experiencing: 

I tried saving my rating for SMI adviser again on mindapps and I'm getting an error message that says "Error processing data. Table: applications". Also tried this in incognito mode to make sure it wasn't a cache issue and still getting the same error.

**Comment by cvanem** [comment]
@ecamach13 

It looks like there was a bug introduced by some changes to the google app store. I upgraded the packages for the app store scraper lambda calls to correct the issue.

I created a test app rating and everything works for my account after the update.  Please try again and let me know if you still have problems.

**Comment by cvanem** [comment]
This has been received (communications via email)
