### ISSUE TITLE
Duplicate surveys 

### ISSUE THREAD

**Issue by ecamach13** [BIDMCDigitalPsychiatry/AppMapDB#110]
When looking at the surveys tab under 'admin', there seem to be a lot of duplicates at the same time. I have attached an image.
<img width="1436" alt="Screen Shot 2022-01-18 at 9 53 43 AM" src="https://user-images.githubusercontent.com/70787908/149960778-9c5fbb86-e628-49b7-a372-f74ce7c8ecb7.png">
 
The individual below is the biggest offender. I'm not sure if they click on submit too much or refresh the screen or what but they submitted a ton. In addition to the repeated timestamps, it is clear this individual is a 'troll' as they sometimes change their gender / race in the surveys. Is there a way we can delete or archive these unwanted submissions? 
<img width="1420" alt="Screen Shot 2022-01-18 at 9 54 07 AM" src="https://user-images.githubusercontent.com/70787908/149960878-fdfecaa8-06ac-4b6c-a2c4-47520a344509.png">

**Comment by cvanem** [comment]
@ecamach13 
There was a bug in the code that didn't disable the submit button when submitting, so users were able to press it multiple times.

I fixed the bug and also deleted duplicate entries in the database.

I also added a feature request to allow deleting surveys in the next version: #111
