### ISSUE TITLE
Add a 'Team' tab in community

### ISSUE THREAD

**Issue by ecamach13** [BIDMCDigitalPsychiatry/AppMapDB#112]
We would like to add a 'Team' tab 
When you click community, it can appear to the right of the calendar 
I want to be able to add captions to their images as an admin
I want to be able to edit the order of the team as an admin

this is the way we have posted our team images in the past but we are open to anything: https://www.digitalpsych.org/people.html

**Comment by cvanem** [comment]
@ecamach13 

There are two ways to do this:

1. We can hard code all of the user information into the source code and you can update a description file as needed for the captions or to add/remove/organize team members.  This will take me about 4 hours to implement

2. I can create a managed database solution where the admin has the ability to add/edit/remove/organize team members as needed within the web application.  This will probably take about 12 hours to implement.

Please let me know which option you would like?

**Comment by ecamach13** [comment]
I think we're imagining something that can be edited, as the volunteers are constantly changing. I think the second option where we can add/edit/remove/reorganize members is what we're looking for. Does this need another invoice? If so, send it my way

**Comment by cvanem** [comment]
@ecamach13 No invoice needed yet.  Let's see where we get with the remaining hours.  I still haven't started the Quiz or First Time Use tasks.

**Comment by cvanem** [comment]
TODO:

- [x] Add ability to define order of team members.
- [x] Add empty image placeholder
- [x] Add s3 upload
- [x] Create database table
- [x] Create teams page and integrate tab
- [x] Create grid view for teams page.
- [x] Create grid item card for team member.
- [x] Create team member form for new members and edit existing members.
- [x] Support delete and show archived.

**Comment by cvanem** [comment]
@ecamach13 This has been completed and published.   Let me know if you have any questions or issues.

**On the Community -> Team page:**
- To add new team members, login as admin and click add new team member.
- To update sort positions log in as admin and click show sort keys.  Must be at least one member in the list.
