### ISSUE TITLE
Remaining Tasks/Misc Issues

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/AppMapDB#19]
**Low Priority Remaining**
- [x] Integrate search into filter popover.
- [x] Integrate text search into advanced filters tab on home page.
- [x] Adjust width of rating history column for non admin user on the regular grid view
- [x] Add rating history count to the rating history button.

**Remaining:**
- [x] Transfer firebase authentication site to BIDMC
- [x] Production deployment of cloud functions. **The current CORS proxy is deployed on my 
- [x] Move table toolbar buttons to a floating action button
- [x] Hide approve button in public mode when logged in as admin.
- [x] Adjust main grid to show all entries in admin mode and the user is signed in.
- [x] Adjust main grid to show only the most recently approved entry for each row when displayed to the public.
- [x]  Also add a column/text to show the approval status.
- [x] Implement Approve Action (update the item)
- [x] Hide rating history on history views
- [x] fix search color when toolbar when viewing history (Search button removed)
- [x] Implement viewing public.
- [x] Change ui colors for admin mode
- [x] Add application history dialog and grid/list history tables.  
- [x] Add groupId and configurable table toolbar position. 
personal google cloud account.  It should be moved under BIDMC)**
- [x] Remove all references to ratings database in couchdb and code. We no longer need it.
personal GCP account.  This will need to be deployed somewhere else for production.  Can this be deployed under the production AWS account?**
- [x] Update homepage in package.json to point to deployment target.
- [x] Update Rate App Column, we no longer need the number of reviews as the link will edit the existing entry.
- [x] Reseed development
- [x] Reseed production
- [x] Fix column widths in table view.
- [x] Add steps for input, output, supported conditions or add tooltips for multi select options (inputs/outputs).
- [x] Update app summary to show multiple costs/developer types.
- [x] Fix Rate New App dialog layouts
- [x] Add app link for android, web and apple tabs
- [x] Connect ListView rate app link to rate app dialog and allow edit mode
- [x] Add edit functionality to RateNewApp
- [x] Add tooltips/help for questions
- [x] Create Yes/No input components
- [x] Add privacy step
- [x] Update back-end code and db models to support multiple developer types.
- [x] Application Origin Step - Convert to multiple select type.
- [x] Update list view to support multiple developer types.
- [x] Move Framework and Questions - We can remove the “Framework and Questions” from the navigation bar at the top. The information that is currently under that link can replace the introductory video on the homepage.
- [x] Add a home page (and remove the getting started dialog).

- [x] Remove the following filter options: 
“Well written and relevant content”
“App appears to do what it claims”
“Can respond to harm”
“Third party vendors”
“Inputs”
“Outputs”

- [x] Remove star rating from app image display but keep the review option and rate the app.

- [x] Change privacy chips from red to pink.

- [x] Compress the chips if > 3 items exist.  This will consist of an ... X More chip if > 3 items exist.

- [x] Move the filter and search functionality above the table/list view.

- [x] hide the app rating from UI but keep it in the data 
**I believe this has already been completed, but correct me if I am wrong?  The Rate New App dialog should no longer prompt the user for a rating at the end of the process.  The rating can be left by clicking the Rate App link within the data.   If this is referring to something else, can you please elaborate?  You may need to refresh your browser if you aren't seeing this behavior on the live site.** 

- [x] be able to hide columns as admins; basically, be able to add/remove column at will for data
**We currently don't have authentication or admin accounts implemented in this project so we need to clarify how to implement this or if additional functionality should be added.  Here are the options I can see, let me which one you would like or if you have something else in mind:**     
1. **Add the ability for a user to enable/disable columns on the table view for their browser.  This would apply to each user individually and would work on the table view only (not list view).** **This has been abandoned for now as we don't have admin user support added yet**

2. **We could add a database table and have an admin user update the database manually.  This table could then be used to show filter columns for all users.**

3. **Add some type of admin authentication scheme + database table + an admin only UI to select columns.**

- [x] less horizontal scroll for the list view.  **To limit the horizontal scroll, the layout was adjusted to use a responsive virtual list with a dynamic row height.  The chips will now re-size and adjust automatically according to the screensize.**
![image](https://user-images.githubusercontent.com/24579103/75993498-c88d8c80-5eb6-11ea-9bab-67b89b0c56f4.png)

- [x] show number of tags for each category list view and click to expand and show the items themselves.  **The chip layout has been adjusted to automatically stack chips so they can all fit within the view (see above).  We previously had the numbers shown for each category, but removed them.  Are we looking to add that back.  I am assuming this is resolved with the new layout, but let me know if not.

- [x] show the date last updated for each item - Added updated field to applications and show in application tables.

- [x] make filters appear at the top of main page and not as a hidden popup.  **Ok, I will look into a few options to see what looks good.  The initial reasoning for moving the filters into a popup was to provide more screen real estate for the data, especially on smaller screens/mobile views.  We can definitely move the filters to the top of the page but it will effect the screen space.  We may still want to show a compressed or popup view for small screens.   I will see what I can come up with.**

- [x] move the search into the filter area and also remove question mark thing on the right side of the table (only button should be swap between table and list)
**Do we want to completely remove the question mark icon or should we move it somewhere else, like into the header bar?  The question mark opens the getting started dialog which contains the video for the user to view.  This dialog is automatically shown the first time the application is open and can be opened any time after that by clicking on the button.  If we remove the question mark button completely, then there will be no way to open the dialog after the initial page load.  Please let me know the desired behavior.**  

**Remaining Tasks:**
---

1. - [x] **Enhance layout for list view app summary component.** The list view layout needs to be updated to display the new db field information as well as improve the current layout.  **This has been completed and now shows the new database fields**

2. - [x] **Review & Itemize Revisions or Changes:** I would like to get a review of the current application state and rating/review workflow to ensure it is meeting the intended design and functionality requirements.  If reviews or changes are needed, it would be helpful to itemize these so they can be incorporated into the development plan.
 
3. - [x] **Content for Framework & Questions Page:** Need to determine what content will go here?

4. - [x] **Content for Rating Process:** Need to determine what content will go here?  We may not need this page as the Rate New App page should be fairly self explanatory.

5. - [x] **Determine Web Store:** If web is the only platform selected, then the user will be prompted with input fields for the name and company.  If an iOS or Android platform is selected in conjunction with the web platform, the name will be taken from the iOS or Android platform.

6. - [x] **Update getting started video link to real video:** The getting started dialog needs to be updated with a link to the real getting started video.  How is this going to be handled? Will I be provided a link or do you need me to create a video? **This has been abandoned**

7. - [x] **Reset Production Database.** Once ready, the production database will need to be deleted and recreated: ratings_production, applications_production.

**Misc Issues:**
---
- [x] Fix table view column widths as we added some settings.
- [x] The table filters seem to sporadically get reset when clicking on the filter button.  **Leaving open for now, but have not been able to reproduce recently.** 
- [x] Fix app bar margin so it matches table margin.
- [x] Determine expected number of applications for database size.  If there are going to be a very 
large number of entries, there are things that can be done to reduce the database size, such as storing values as enums instead of strings.  **This does not appear to be a concern.  If the database size becomes an issue at a later date, we can compress and update as needed**
- [x] Add select input component that allows clearing the selected value.  Currently if Clinical Foundation is selected in the filters, there is no way to reset it other than the reset all button.
- [x] Determine table refresh logic, interval or add a button or leave it how it is, which is requests new data every time it is mounted.  Current implementation: Re-quest data on mount, while inserting new records locally and remotely as they are created.
text search resets the filter options.  The filters should not reset.
- [x] Add http link validation to the RateNewApp dialog fields (links for the app store)
- [x] If there are 0 reviews in the ReviewDialog, then we should have some text that says there are no reviews.  The review dialogs button could also be disabled if there are 0 reviews to prevent it from being opened.
- [x] A few of the filters are broken due to spelling errors and need to be fixed.
- [x] Vertical scroll behavior doesn't work well and scroll bars display incorrectly in the headers on Firefox.
- [x] Searching for ( or ) characters cause an error.
- [x] Upon submission of new app, re-direct to the applications table.
- [x] Update filters to include new database fields.

**Comment by avaidyam** [comment]
@cvanem Which of the two cloud functions is the one in use? Seems like they both do the same thing but one of them supports Google Play Store as well?

**Comment by cvanem** [comment]
@avaidyam I'm not sure how that got there, it must have been an old copy.  Use the one in the app-store-cors-proxy folder.  You will need the package.json file that is included with it also.  I removed the un-used one.
