### ISSUE TITLE
Outstanding Questions

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/AppMapDB#36]
- [x] The Framework page in the documentation shows two videos, but the old website only has 1 video.  Where can I locate the content for the 'Actual App Evaluation' video?
**The "Actual App Evaluation" video is the video that is currently on the "rate an app" section of the website. We can rename the "Actual App Evaluation" to "Example App Evaluation."**
- [x] The videos for the Framework page list a date for each video.  Is this needed or can it be removed?  If so, what date would you like for each of the videos? **Date is not needed for videos!**
![image](https://user-images.githubusercontent.com/24579103/102097875-b21c4600-3de3-11eb-83c6-52f799bd3a71.png)

- [x] The documentation for the footer website (see above screenshot - bottom right) mentions a privacy policy.  Is this needed?  If so, where can I locate the content for this link?

- [x] On the home page as seen below, there are a number of Feature tags.  What is the desired behavior for this section? 
    - [x] Should these be individually selectable?  
    - [x] If so, what should happen when the user selects them?  Should they just change to a different color and have a remove button if they are active?  I want to make sure I understand the desired implementation correctly.  If you would rather that I just come up with an acceptable solution let me know and I can provide a solution that fits best.
![image](https://user-images.githubusercontent.com/24579103/101853195-74d26280-3b1c-11eb-9acb-eba67ef33da9.png)

**Comment by slagan1** [comment]
> * [x]  The Framework page in the documentation shows two videos, but the old website only has 1 video.  Where can I locate the content for the 'Actual App Evaluation' video?
_**The "Actual App Evaluation" video is the video that is currently on the "rate an app" section of the website. We can rename the "Actual App Evaluation" to "Example App Evaluation."**_
> * [x]  The videos for the Framework page list a date for each video.  Is this needed or can it be removed?  If so, what date would you like for each of the videos?
**_Date is not needed for videos!_**
> * [x]  The documentation for the footer website (see above screenshot - bottom right) mentions a privacy policy.  Is this needed?  If so, where can I locate the content for this link?
**_No, this is not needed at this time_**
> * [x]  On the home page as seen below, there are a number of Feature tags.  What is the desired behavior for this section?
>   
>   * [x]  Should these be individually selectable?
**_Yes, they should be individually selectable_**
>   * [x]  If so, what should happen when the user selects them?  Should they just change to a different color and have a remove button if they are active?  I want to make sure I understand the desired implementation correctly.  If you would rather that I just come up with an acceptable solution let me know and I can provide a solution that fits best.
_**My thought was the same as you - they'll just change to a different color when selected. Let me know if you think this is the best solution. **_
