### ISSUE TITLE
On the news section, subtitle repeats three times where it should only appear once.

### ISSUE THREAD

**Issue by slagan1** [BIDMCDigitalPsychiatry/AppMapDB#65]
https://github.com/BIDMCDigitalPsychiatry/AppMapDB/blob/c6d3398b6cc6dddb2d92b9266b801e8b73654cbd/src/components/pages/News/NewsV2.tsx#L78

**Comment by cvanem** [comment]
This has been fixed

**Comment by jtorous** [comment]
Thanks Chris!

-John
