### ISSUE TITLE
Compromised AWS Access Key

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/AppMapDB#68]
I just received an AWS security email that the access key named `appmap` was compromised. It only had outgoing SES enabled for it, so not a huge security issue, but please remove it and let me know if you need a new one added as a GitHub secret on this repository.

**Comment by cvanem** [comment]
@avaidyam How was the key compromised?  Was it via the repository source or somewhere else?  I don't see it being used anywhere.  Either way, I disabled the access key for the appmap user, which should address your issue.   This key was used for the the initial setup with the amplify cli, so it doesn't need to be active.

![image](https://user-images.githubusercontent.com/24579103/112669754-aea64b00-8e25-11eb-956f-17d7ef62d83f.png)

**Comment by avaidyam** [comment]
@cvanem I couldn't figure out what happened either. Thanks for disabling it -- I think we're all good now! //cc @slagan1
