### ISSUE TITLE
Add additional questions

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/AppMapDB#72]
The document below references additional question content is to be provided: https://docs.google.com/document/d/1mueDJ9rcrbnOKe_0I1vI293HKslfAGyi2l9Hbb2iHR4/edit

This is a placeholder task.  Additional question content is TBD.   Please provide additional question content as needed.  Once provided it can be added.

**Comment by ecamach13** [comment]
We're waiting on responses from our collaborators on what questions to add. As soon as we know I'll add them here.
