### ISSUE TITLE
Link for Research Study

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/AppMapDB#78]
This document references a need for the ability to enter a research study: https://docs.google.com/document/d/1mueDJ9rcrbnOKe_0I1vI293HKslfAGyi2l9Hbb2iHR4/edit

When creating an app review, the user can currently enter a url for both feasibility and efficacy studies if a number > 0 is entered:
![image](https://user-images.githubusercontent.com/24579103/120574071-d85a9000-c3db-11eb-94d1-a00f186e91b0.png)

 Is this sufficient or do we need to add another url input for research studies?  If you can provide some clarification on wording and placement, I can add the associated logic.

- [ ] Ability to enter a link for a research study

**Comment by ecamach13** [comment]
You can disregard this issue, the link we have already is great.

**Comment by cvanem** [comment]
Ok great, closing issue.
