### ISSUE TITLE
Community tab changes

### ISSUE THREAD

**Issue by ecamach13** [BIDMCDigitalPsychiatry/AppMapDB#91]
- [x] Rename the 'educational' tab to 'forum'
- [x] Remove the 'announcements' tab
- [x] User's must be logged in to leave comments
- [x] Add reply button and group replies under parent comment.

**Comment by ecamach13** [comment]
Remove the 'announcements' tab

**Comment by ecamach13** [comment]
Under the 'forum' tab we can keep it that only admins create new posts for discussion. But then non-admins can comment / reply to it. John would like only people with accounts / logged in to be able to add comments. Anyone (logged in or not) can view all of the forum comments.

**Comment by cvanem** [comment]
@ecamach13 The above updates have been completed
