### ISSUE TITLE
In the calendar the word 'every' is written twice

### ISSUE THREAD

**Issue by ecamach13** [BIDMCDigitalPsychiatry/AppMapDB#95]
<img width="343" alt="Screen Shot 2021-06-09 at 8 53 27 AM" src="https://user-images.githubusercontent.com/70787908/121418179-b1024680-c938-11eb-97a0-ad1a3d87d339.png">

**Comment by cvanem** [comment]
I do not see the word "every" written twice in the above screenshot.  More detail/investigation is needed.

**Comment by ecamach13** [comment]
Oh my gosh my apologies !! I got confused with event and every hahha
