### ISSUE TITLE
forum part 2

### ISSUE THREAD

**Issue by ecamach13** [BIDMCDigitalPsychiatry/AppMapDB#97]
when you send a reply it doesn't show up under the comment. Instead it shows up as a new comment. We would like it to be connected / under the original comment. 
<img width="1192" alt="Screen Shot 2021-06-10 at 11 04 00 AM" src="https://user-images.githubusercontent.com/70787908/121549244-af3d8f00-c9db-11eb-9882-b8a80cbdf193.png">

**Comment by ecamach13** [comment]
<img width="1296" alt="Screen Shot 2021-06-10 at 11 05 53 AM" src="https://user-images.githubusercontent.com/70787908/121549403-d5632f00-c9db-11eb-8ff5-23ddea5a1be9.png">
 also can we make the images from the forum appear much smaller. They make it hard to see that there are any comments because you have to scroll.

**Comment by cvanem** [comment]
**TODO** 
- [x]  Comment replies show up directly under their parent comment.  They are indented to further accent the parent/child hierarchy.  The status will also say "replied" instead of commented. 
- [x] Decrease size of forum images
